# Generated by Django 6.0.1 on 2026-01-08 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poggle_play', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrangement', models.JSONField(blank=True, default=list)),
                ('link', models.CharField(unique=True)),
                ('password', models.CharField(blank=True)),
            ],
        ),
    ]
