# Generated by Django 6.0.1 on 2026-01-18 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poggle_play', '0002_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='valid',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='password',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Word_Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='poggle_play.board')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='poggle_play.player')),
                ('word', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='poggle_play.word')),
            ],
        ),
    ]
