# Generated by Django 6.0.1 on 2026-01-18 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poggle_play', '0003_word_valid_alter_board_password_word_board'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='word',
            new_name='word_string',
        ),
    ]
